package main.java.model;
// Generated 20 Apr, 2018 1:51:22 PM by Hibernate Tools 3.6.0.Final

/**
 * Item generated by hbm2java
 */
public class Item implements java.io.Serializable {

	private Integer itemId;
	private Menu menu;
	private String itemName;
	private String itemDescription;
	private Double itemPrice;

	public Item() {
	}

	public Item(Menu menu, String itemName) {
		this.menu = menu;
		this.itemName = itemName;
	}

	public Item(Menu menu, String itemName, String itemDescription, Double itemPrice) {
		this.menu = menu;
		this.itemName = itemName;
		this.itemDescription = itemDescription;
		this.itemPrice = itemPrice;
	}

	public Integer getItemId() {
		return this.itemId;
	}

	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public String getItemDescription() {
		return this.itemDescription;
	}

	public void setItemDescription(String itemDescription) {
		this.itemDescription = itemDescription;
	}

	public Double getItemPrice() {
		return this.itemPrice;
	}

	public void setItemPrice(Double itemPrice) {
		this.itemPrice = itemPrice;
	}

}
