package main.java.model;
// Generated 20 Apr, 2018 1:51:22 PM by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu implements java.io.Serializable {

	private Integer menuId;
	private String menuType;
	private Set<RestMenu> restMenus = new HashSet<RestMenu>(0);
	private Set<Item> items = new HashSet<Item>(0);

	public Menu() {
	}

	public Menu(String menuType) {
		this.menuType = menuType;
	}

	public Menu(String menuType, Set<RestMenu> restMenus, Set<Item> items) {
		this.menuType = menuType;
		this.restMenus = restMenus;
		this.items = items;
	}

	public Integer getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	public String getMenuType() {
		return this.menuType;
	}

	public void setMenuType(String menuType) {
		this.menuType = menuType;
	}

	public Set<RestMenu> getRestMenus() {
		return this.restMenus;
	}

	public void setRestMenus(Set<RestMenu> restMenus) {
		this.restMenus = restMenus;
	}

	public Set<Item> getItems() {
		return this.items;
	}

	public void setItems(Set<Item> items) {
		this.items = items;
	}

}
