package main.java.model;
// Generated 20 Apr, 2018 1:51:22 PM by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Restaurants generated by hbm2java
 */
public class Restaurants{

	private Integer restaurantId;
	private String restaurantName;
	private String restaurantAddress;
	private Float restaurantStars;
	private Set<RestMenu> restMenus = new HashSet<RestMenu>(0);

	public Restaurants() {
	}

	public Restaurants(String restaurantName) {
		this.restaurantName = restaurantName;
	}

	public Restaurants(String restaurantName, String restaurantAddress, Float restaurantStars,
			Set<RestMenu> restMenus) {
		this.restaurantName = restaurantName;
		this.restaurantAddress = restaurantAddress;
		this.restaurantStars = restaurantStars;
		this.restMenus = restMenus;
	}

	public Integer getRestaurantId() {
		return this.restaurantId;
	}

	public void setRestaurantId(Integer restaurantId) {
		this.restaurantId = restaurantId;
	}

	public String getRestaurantName() {
		return this.restaurantName;
	}

	public void setRestaurantName(String restaurantName) {
		this.restaurantName = restaurantName;
	}

	public String getRestaurantAddress() {
		return this.restaurantAddress;
	}

	public void setRestaurantAddress(String restaurantAddress) {
		this.restaurantAddress = restaurantAddress;
	}

	public Float getRestaurantStars() {
		return this.restaurantStars;
	}

	public void setRestaurantStars(Float restaurantStars) {
		this.restaurantStars = restaurantStars;
	}

	public Set<RestMenu> getRestMenus() {
		return this.restMenus;
	}

	public void setRestMenus(Set<RestMenu> restMenus) {
		this.restMenus = restMenus;
	}

}
